job_search_task:
  description: >
    Search for job openings that match the given title. 
    Provide a list of job title, company, and job descriptions.
  expected_output: >
    A markdown file with list of job titles, comapny names, and job descriptions.
    Location of markdown file : {outputs_path}
    Name of markdown file : {jobs_filename}
  agent: job_search_agent

resume_tailor_task:
  description: >
    Access the markdown file from the markdown file path to read the job titles and descriptions.
    Each job title follows **Title** or **Job Title** specifier and each job description follows **Description** specifier.
    The company name follows the **Company** specifier.
    Tailor the candidate's resume to highlight the skills and experience most relevant to a specific job description.
    Markdown file name : {jobs_filename}
    Markdown file path : {outputs_path}
    The resume to tailor is: {resume}
  expected_output: >
    Create a new resume in markdown format as per each job description.
    Save each markdown file in a specified folder with file name as name of the company and .md extension.
    A full resume with all main sections tailored to match the job description.
    Location to save resumes : {resumes_path} 
  agent: resume_tailor_agent

cover_letter_writer_task:
  description: >
    Access the markdown file from the markdown file path to read the job titles and descriptions.
    Each job title follows **Title** or **Job Title** specifier and each job description follows **Description** specifier.
    The company name follows the **Company** specifier.
    Tailor the candidate's cover letter to highlight the skills and experience most relevant to a specific job description.
    Markdown file name : {jobs_filename}
    Markdown file path : {outputs_path}
    The cover letter to tailor is: {cover_letter}
  expected_output: >
    Create a new cover letter in markdown format as per each job description.
    Save each markdown file in a specified folder with file name as name of the company and .md extension.
    A complete cover letter highlighting the candidate's qualities, interests, and enthusiasm to join the company.
    Location to save resumes : {cover_letters_path} 
  agent: cover_letter_writer_agent

interview_prep_task:
  description: >
    Access the markdown file from the markdown file path to read the job titles and descriptions.
    Each job title follows **Title** or **Job Title** specifier and each job description follows **Description** specifier.
    The company name follows the **Company** specifier.
    Generate interview questions based on the job description for each job.
    Markdown file name : {jobs_filename}
    Markdown file path : {outputs_path}
  expected_output: >
    A list of interview questions for the candidate based on job descriptions.
    Save each markdown file in a specified folder with file name as name of the company and .md extension.
    Location to save resumes : {interview_questions_path} 
  agent: interview_prep_agent
